# Generated by Django 2.2.7 on 2019-11-18 15:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityName', models.CharField(help_text='Enter community name', max_length=100, null=True)),
                ('communityDesc', models.CharField(help_text='Enter community description', max_length=200, null=True)),
                ('communitySemanticTag', models.CharField(help_text='Enter related semantic tag', max_length=100, null=True)),
                ('communityPhoto', models.ImageField(upload_to='communities')),
                ('communityCreationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isActive', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter data type name', max_length=100, null=True)),
                ('maxLength', models.CharField(help_text='Maxlength', max_length=100, null=True)),
                ('isNull', models.CharField(help_text='Can be null?', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(help_text='Enter title of post as text', max_length=100, null=True)),
                ('postBody', models.CharField(help_text='Enter body of post as text', max_length=200, null=True)),
                ('postTag', models.CharField(help_text='Tag comes from related community tag', max_length=100, null=True)),
                ('isActive', models.BooleanField(null=True)),
                ('postCreationDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTypeName', models.CharField(help_text='Enter post type name', max_length=100, null=True)),
                ('postTypeDesc', models.CharField(help_text='Enter post type description', max_length=1200, null=True)),
                ('isActive', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='Enter your name', max_length=50, null=True)),
                ('userSurname', models.CharField(help_text='Enter your surname', max_length=50, null=True)),
                ('userMail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(help_text='Enter your password', max_length=50, null=True)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('userPhoto', models.ImageField(blank=True, upload_to='users')),
                ('isActive', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('relatedPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='relatedCommunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Community'),
        ),
        migrations.AddField(
            model_name='post',
            name='relatedPostType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.PostType'),
        ),
        migrations.AddField(
            model_name='community',
            name='communityMembers',
            field=models.ManyToManyField(help_text='Community members', related_name='members', to='community.User'),
        ),
        migrations.AddField(
            model_name='community',
            name='communityOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='community.User'),
        ),
    ]
