# Generated by Django 2.2.7 on 2019-12-22 05:42

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Community Name', max_length=100, null=True)),
                ('description', models.CharField(help_text='Enter Community Description', max_length=200, null=True)),
                ('community_photo', models.ImageField(upload_to='Communities')),
                ('published_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_communities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTypeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Post Name', max_length=200)),
                ('description', models.CharField(help_text='Enter Post Description', max_length=200)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('publish_date', models.DateTimeField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Title of Post As Text', max_length=100, null=True)),
                ('body', models.CharField(help_text='Enter Body of Post As Text', max_length=200, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('semantic_tag', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_active', models.BooleanField(null=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.PostTypeObject')),
            ],
        ),
    ]
