# Generated by Django 2.2.7 on 2019-11-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posttype',
            name='related_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_communities', to='community.Community'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='semantic_tag',
            field=models.CharField(help_text='Enter related semantic tag', max_length=100, null=True),
        ),
    ]
