# Generated by Django 2.2.7 on 2019-12-11 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191119_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='max_length',
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='enumeration',
            field=models.CharField(help_text='Enter the Enumerations', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='is_enum',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='is_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='relatedPostType',
            field=models.ForeignKey(help_text='Select related post type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.PostType'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.User'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='semantic_code',
            field=models.CharField(help_text='Enter related semantic tag', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='semantic_tag',
            field=models.CharField(help_text='Enter related semantic tag', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='semantic_tag',
            field=models.CharField(help_text='Enter related semantic tag', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PostTypeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.PostType')),
            ],
        ),
    ]
