# Generated by Django 2.2.7 on 2019-12-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20191211_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldType',
        ),
    ]
