# Generated by Django 2.2.7 on 2019-12-13 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_delete_fieldtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttypeobject',
            name='data_type',
        ),
        migrations.AddField(
            model_name='posttypeobject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posttypeobject',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
